name: Trigger Issue on English Changes with Visual Diff

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed


jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
          fetch-depth: 2

    - name: Generate Visual Diff
      id: generate
      run: |
        set -e
        set -o pipefail
        # Check if changes were made to the "en/" folder
        if git diff --quiet HEAD~1 main -- 'en/'; then
          echo "No changes in the 'en/' folder."
          echo "::set-output name=changes-exists::false"
        else
          # Generate a visual diff of the changes in the "en/" folder.
          echo "::set-output name=changes-exists::true"
          message="Visual Diff of Changes:\n\n\`\`\`\n$(git diff HEAD~1 main -- 'en/')\n\`\`\`"
          echo "::set-output name=content::$message"
        fi


    - name: Create Issue
      if: steps.generate.changes-exists == 'true'
      uses: actions/create-issue@v1
      with:
        title: Translation needed
        body: ${{ steps.generate.outputs.content }}