name: Trigger Issue on English Changes with Visual Diff

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

permissions:
  issues: write

jobs:
  create-issue-on-english-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with:
          fetch-depth: 2

    - name: Generate Visual Diff
      run: |
        set -e
        set -o pipefail
        # Check if changes were made to the "en/" folder
        if git diff --quiet HEAD~1 main -- 'en/'; then
          echo "No changes in the 'en/' folder."
        else
          # Generate a visual diff of the changes in the "en/" folder.
          message="Visual Diff of Changes:\n\n\`\`\`diff\n$(git diff HEAD~1 main -- 'en/')\n\`\`\`"
          echo $message > ./visual_diffs
        fi

    - name: Create new issue
      uses: imjohnbo/issue-bot@v3
      with:
        title: Hello, world
        body: |-
          :wave: Hi, all !
        pinned: true